apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  namespace: cloudacademy
spec:
 rules:
 - host: frontend.157.230.67.183.nip.io
   http:
     paths:
     - path: /
       backend:
         serviceName: frontend
         servicePort: 80