kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-to-mongo-from-api
  namespace: cloudacademy
spec:
  podSelector:
    matchLabels:
      role: db
  ingress:
  - from:
      - podSelector:
          matchLabels:
            role: api